#!/bin/bash
# Restore xfce4-keyboard-shortcuts (custom commands)
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Alt>F1" -t string -s "xfce4-popup-applicationsmenu"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Alt>F2" -t string -s "xfce4-appfinder --collapsed"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Alt>F3" -t string -s "xfce4-appfinder"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Primary><Alt>Delete" -t string -s "xfce4-session-logout"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Primary><Alt>o" -t string -s "onboard"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Primary><Alt>t" -t string -s "x-terminal-emulator -t "Command Line""
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Primary>Escape" -t string -s "xfdesktop --menu"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Primary><Shift>Escape" -t string -s "/usr/bin/system-monitoring-center"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/Print" -t string -s "xfce4-screenshooter"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super><Alt>Return" -t string -s "alacritty -e tmux new -A -s Work"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>F1" -t string -s "$HOME/.local/bin/omarchy-keybinds"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>h" -t string -s "exo-open --launch FileManager"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>l" -t string -s "xflock4"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>p" -t string -s "xfce4-display-settings --minimal"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>Return" -t string -s "alacritty"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super><Shift>b" -t string -s "chromium"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super><Shift>f" -t string -s "exo-open --launch FileManager"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super><Shift>n" -t string -s "alacritty -e nvim"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/<Super>Space" -t string -s "rofi -show drun"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/XF86Display" -t string -s "xfce4-display-settings --minimal"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/XF86Mail" -t string -s "exo-open --launch MailReader"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/commands/custom/XF86WWW" -t string -s "chromium"

# Restore xfwm4 custom keybindings
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>Delete" -t string -s "del_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F10" -t string -s "maximize_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F11" -t string -s "fullscreen_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F12" -t string -s "above_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F4" -t string -s "close_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F6" -t string -s "stick_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F7" -t string -s "move_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F8" -t string -s "resize_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>F9" -t string -s "hide_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>Insert" -t string -s "add_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt><Shift>Tab" -t string -s "cycle_reverse_windows_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>space" -t string -s "popup_menu_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Alt>Tab" -t string -s "cycle_windows_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/Down" -t string -s "down_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/Escape" -t string -s "cancel_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/Left" -t string -s "left_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>d" -t string -s "show_desktop_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>Down" -t string -s "down_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>End" -t string -s "move_window_next_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>Home" -t string -s "move_window_prev_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_1" -t string -s "move_window_workspace_1_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_2" -t string -s "move_window_workspace_2_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_3" -t string -s "move_window_workspace_3_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_4" -t string -s "move_window_workspace_4_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_5" -t string -s "move_window_workspace_5_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_6" -t string -s "move_window_workspace_6_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_7" -t string -s "move_window_workspace_7_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_8" -t string -s "move_window_workspace_8_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>KP_9" -t string -s "move_window_workspace_9_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>Left" -t string -s "left_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>Right" -t string -s "right_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Alt>Up" -t string -s "up_workspace_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F1" -t string -s "workspace_1_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F10" -t string -s "workspace_10_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F11" -t string -s "workspace_11_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F12" -t string -s "workspace_12_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F2" -t string -s "workspace_2_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F3" -t string -s "workspace_3_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F4" -t string -s "workspace_4_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F5" -t string -s "workspace_5_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F6" -t string -s "workspace_6_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F7" -t string -s "workspace_7_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F8" -t string -s "workspace_8_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary>F9" -t string -s "workspace_9_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Shift><Alt>Left" -t string -s "move_window_left_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Shift><Alt>Right" -t string -s "move_window_right_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Primary><Shift><Alt>Up" -t string -s "move_window_up_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/Right" -t string -s "right_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Shift><Alt>Page_Down" -t string -s "lower_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Shift><Alt>Page_Up" -t string -s "raise_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Super>q" -t string -s "close_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Super>Q" -t string -s "close_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/<Super>Tab" -t string -s "switch_window_key"
xfconf-query -c xfce4-keyboard-shortcuts -n -p "/xfwm4/custom/Up" -t string -s "up_key"
